# Generated by Django 4.2.7 on 2025-06-29 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Filière',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('type_salle', models.CharField(choices=[('COURS', 'Cours magistral'), ('TP', 'Travaux pratiques'), ('TD', 'Travaux dirigés'), ('AMPHI', 'Amphithéâtre')], max_length=50)),
                ('equipements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('specialite', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('heures_total', models.IntegerField(help_text="Nombre d'heures total du cours")),
                ('description', models.TextField(blank=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.filiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=20)),
                ('nombre_etudiants', models.IntegerField(default=0)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_seance', models.CharField(choices=[('COURS', 'Cours'), ('TD', 'TD'), ('TP', 'TP'), ('EXAM', 'Examen')], max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.cours')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.salle')),
            ],
            options={
                'unique_together': {('salle', 'date', 'heure_debut'), ('cours', 'date', 'heure_debut')},
            },
        ),
    ]
