# Generated by Django 4.2.7 on 2025-06-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='professeur',
            field=models.CharField(max_length=100),
        ),
    ]
